# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='pwd',
        ),
    ]
