# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20180822_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='cid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='pwd',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='pwd',
            field=models.CharField(max_length=6),
        ),
    ]
