# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20180822_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pwd',
        ),
    ]
