# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20180822_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_1', models.IntegerField(default=0)),
                ('class_2', models.IntegerField(default=0)),
                ('class_3', models.IntegerField(default=0)),
                ('class_4', models.IntegerField(default=0)),
                ('day_off', models.IntegerField(default=0)),
            ],
        ),
    ]
