# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20180822_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField(default=0)),
                ('coach', models.IntegerField(default=0)),
                ('class_time', models.IntegerField(default=0)),
            ],
        ),
    ]
