# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
