# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20180823_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
